#!/bin/env python
# -*- coding: utf-8 -*-
"""
lgr_harmonized.py - CLI tool to perform LGR harmonization
"""
from __future__ import unicode_literals

import logging
import os

from lgr.parser.xml_serializer import serialize_lgr_xml
from lgr.tools.harmonize import harmonize
from lgr.tools.utils import write_output
from lgr.utils import format_cp, cp_to_ulabel
from tools.utils import LgrToolArgParser, parse_lgr

logger = logging.getLogger("lgr_harmonize")


def main():
    parser = LgrToolArgParser(description='LGR Harmonize CLI')
    parser.add_common_args()
    parser.add_argument('-1', '--first', help='First LGR to harmonize', required=True)
    parser.add_argument('-2', '--second', help='Second LGR to harmonize', required=True)
    parser.add_argument('-z', '--root-zone', help='Rootzone LGR to infer variants from')
    parser.add_argument('output', help='Output directory to place generated LGR')

    args = parser.parse_args()
    parser.setup_logger()

    unidb = parser.get_unidb()

    first_lgr, second_lgr = parse_lgr(args.first, args.rng, unidb), parse_lgr(args.second, args.rng, unidb)
    rz_lgr = None
    if args.root_zone:
        rz_lgr = parse_lgr(args.root_zone, args.rng, unidb)

    first_h, second_h, (log_first, log_second) = harmonize(first_lgr, second_lgr, rz_lgr)

    for lgr in (first_h, second_h):
        xml = serialize_lgr_xml(lgr)
        if lgr.name.endswith('.xml'):
            name = lgr.name[:-4] + '_harmonized.xml'
        else:
            name = lgr.name + '_harmonized'
        with open(os.path.join(args.output, name), 'wb') as f:
            f.write(xml)

    # Handle log output
    def _process_log(log):
        for cp in log:
            write_output("- {} ({})".format(format_cp(cp), cp_to_ulabel(cp)))

    write_output("Manual review needed for code points from first LGR:")
    _process_log(log_first)
    write_output("Manual review needed for code points from second LGR:")
    _process_log(log_second)


if __name__ == '__main__':
    main()
